version: '3.7'

services:
  app:
    depends_on:
      - db
    image: poins
    container_name: poins
    hostname: poins
    build:
      context: .
    ports:
      - 8001:8001
    volumes:
      - .:/app
      - /app/vendor
    stdin_open: true
    tty: true
    command: php artisan serve --host 0.0.0.0 --port 8001
    networks:
      - poins
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=poins
      - DB_USERNAME=poins
      - DB_PASSWORD=bismillah

  db:
    image: mysql
    container_name: poins_db
    hostname: poins_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db.sql:/db.sql
    environment:
      MYSQL_ROOT_PASSWORD: bismillah
      MYSQL_DATABASE: poins
      MYSQL_USER: poins
      MYSQL_PASSWORD: bismillah
    networks:
      - poins

# delete it to use default networks
networks:
  poins:
    name: poins  
